### ISSUE TITLE
Beware of mutable default arguments

### ISSUE THREAD

**Issue by tleonhardt** [teto/pymptcpanalyzer#10]
* mptcpanalyzer version ($ mptcpanalyzer --version):  **new_plots** branch

I noticed that in a number of functions/methods you have mutable (empty list) default argument values.  Such as the following case in [plots.py](https://github.com/teto/mptcpanalyzer/blob/new_plots/mptcpanalyzer/plot.py) where the **parent_parsers** argument has a mutable default value:
```Python3
def default_parser(
        self,
        parent_parsers=[],
        filterstream: bool = False,
        direction: bool = False, skip_subflows: bool = True,
        dst_host: bool=False,
    ) -> argparse_completer.ACArgumentParser:
```

Python mutable default arguments in functions and methods do NOT behave in a sane way like 99.9% of programmers's would expect.  See this article on [Common Python Gotchas](https://docs.python-guide.org/writing/gotchas/) for more info.  In short, mutable default values for function arguments in Python behave almost identically to static local variables in C/C++.

**Comment by tleonhardt** [comment]
The proper way to do what you want in the above case is like so:
```Python3
def default_parser(
        self,
        parent_parsers=None,
        filterstream: bool = False,
        direction: bool = False, skip_subflows: bool = True,
        dst_host: bool=False,
    ) -> argparse_completer.ACArgumentParser:
        """Docstring"""
        if parent_parsers is None:
            parent_parsers = []
```

Some 3rd-party libraries such as [attrs](http://www.attrs.org/en/stable/overview.html) make it even easier by supporting factory behavior out of the box.

**Comment by teto** [comment]
wow thanks for the warning. that's some shitty (surprising) behavior here. I dont think it has been a problem but I will update the code as you suggest. Thanks !

**Comment by teto** [comment]
I fixed your example and will pay more attention to this in the future. Thanks
