### ISSUE TITLE
Consider providing a tabular display of data in addition to plots

### ISSUE THREAD

**Issue by tleonhardt** [teto/pymptcpanalyzer#11]
Python modules such as [tableformatter](https://github.com/python-tableformatter/tableformatter) can provide very aesthetically pleasing displays of tabular data directly within a command-line application.

You might want to look at that sort of thing as an option.

**Comment by teto** [comment]
thanks for the recommendation. Actually, I have been adding export capabilities to some commands with --json/--csv flags so that users can build upon it. I am not sure printing the columns in the terminal might help (either too much data or a single column would be enough).

**Comment by tleonhardt** [comment]
When using cmd2’s ppaged method in combination with tableformatter, the tabular output gets sent to a pager (less) which allows users to browse through big tables using arrow keys and search.  So the tables can be much wider and much taller than can fit in the screen at once, but users can still browse through them.

**Comment by teto** [comment]
I see tableformatter is one of your project :) 
It definitely looks cool, especially the ability to color cells based on values. It would come in handy to find weird values/help debugging. 
My focus is now to stabilize the software to release a version sometime this month.

**Comment by teto** [comment]
There is too much data for cli I think, let's use libreoffice calc :)
