### ISSUE TITLE
'MpTcpAnalyzerCmdApp' object has no attribute 'statement_parser'

### ISSUE THREAD

**Issue by dreibh** [teto/pymptcpanalyzer#17]
I tried to run mptcpdump on Ubuntu 19.04, after installing it with "pip3 install mptcpanalzyer --user". The installation of mptcpanalyzer and dependencies was successful. But the program does not start:

$ mptcpanalyzer
Setting log level to ERROR
An error happened:
'MpTcpAnalyzerCmdApp' object has no attribute 'statement_parser'
Displaying backtrace:

Traceback (most recent call last):
  File "/home/dreibh/.local/lib/python3.6/site-packages/mptcpanalyzer/cli.py", line 1216, in main
    analyzer = MpTcpAnalyzerCmdApp(config, **vars(args))
  File "/home/dreibh/.local/lib/python3.6/site-packages/mptcpanalyzer/cli.py", line 136, in __init__
    self.shortcuts.update({
  File "/home/dreibh/.local/lib/python3.6/site-packages/cmd2/cmd2.py", line 570, in shortcuts
    return self.statement_parser.shortcuts
AttributeError: 'MpTcpAnalyzerCmdApp' object has no attribute 'statement_parser'

May be the specification of some dependencies is wrong (e.g. required versions of the dependencies)?

**Comment by dreibh** [comment]
This issue could be related to Issue #16.

**Comment by dreibh** [comment]
I am also able to reproduce the problem under Ubuntu 18.04 LTS:

dreibh@oesthorn:~$ pip3 install mptcpanalyzer --user
Collecting mptcpanalyzer
  Downloading https://files.pythonhosted.org/packages/45/a0/0e0ce4722c69ac6831ad7b699a591e99f4f8b7679c3cf9817c27aa67c96f/mptcpanalyzer-0.3-py3-none-any.whl (85kB)
    100% |████████████████████████████████| 92kB 3.7MB/s 
Collecting cmd2>=0.9 (from mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/9d/7c/fc946c24dfe4b12ffdcd099216471c413bbcf48f94f86b91b4ea44ccbaa6/cmd2-0.9.12-py3-none-any.whl (92kB)
    100% |████████████████████████████████| 102kB 8.8MB/s 
Collecting matplotlib (from mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/e9/69/f5e05f578585ed9935247be3788b374f90701296a70c8871bcd6d21edb00/matplotlib-3.0.3-cp36-cp36m-manylinux1_x86_64.whl (13.0MB)
    100% |████████████████████████████████| 13.0MB 87kB/s 
Collecting pandas>=0.23 (from mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/19/74/e50234bc82c553fecdbd566d8650801e3fe2d6d8c8d940638e3d8a7c5522/pandas-0.24.2-cp36-cp36m-manylinux1_x86_64.whl (10.1MB)
    100% |████████████████████████████████| 10.1MB 110kB/s 
Collecting stevedore (from mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/c6/dc/6ee92bccfe3c0448786b30b693e6060d62ec8c4a3ec9a287bac1c1a8d8c9/stevedore-1.30.1-py2.py3-none-any.whl (42kB)
    100% |████████████████████████████████| 51kB 9.4MB/s 
Collecting wcwidth>=0.1.7 (from cmd2>=0.9->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting attrs>=16.3.0 (from cmd2>=0.9->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting colorama (from cmd2>=0.9->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting pyperclip>=1.5.27 (from cmd2>=0.9->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/2d/0f/4eda562dffd085945d57c2d9a5da745cfb5228c02bc90f2c74bbac746243/pyperclip-1.7.0.tar.gz
Collecting numpy>=1.10.0 (from matplotlib->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/c1/e2/4db8df8f6cddc98e7d7c537245ef2f4e41a1ed17bf0c3177ab3cc6beac7f/numpy-1.16.3-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
    100% |████████████████████████████████| 17.3MB 62kB/s 
Collecting kiwisolver>=1.0.1 (from matplotlib->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/69/a7/88719d132b18300b4369fbffa741841cfd36d1e637e1990f27929945b538/kiwisolver-1.0.1-cp36-cp36m-manylinux1_x86_64.whl (949kB)
    100% |████████████████████████████████| 952kB 1.2MB/s 
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl (62kB)
    100% |████████████████████████████████| 71kB 9.3MB/s 
Collecting cycler>=0.10 (from matplotlib->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.1 (from matplotlib->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
    100% |████████████████████████████████| 235kB 4.8MB/s 
Collecting pytz>=2011k (from pandas>=0.23->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 2.2MB/s 
Collecting pbr!=2.1.0,>=2.0.0 (from stevedore->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/14/09/12fe9a14237a6b7e0ba3a8d6fcf254bf4b10ec56a0185f73d651145e9222/pbr-5.1.3-py2.py3-none-any.whl (107kB)
    100% |████████████████████████████████| 112kB 8.4MB/s 
Collecting six>=1.10.0 (from stevedore->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting setuptools (from kiwisolver>=1.0.1->matplotlib->mptcpanalyzer)
  Downloading https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)
    100% |████████████████████████████████| 583kB 2.0MB/s 
Building wheels for collected packages: pyperclip
  Running setup.py bdist_wheel for pyperclip ... done
  Stored in directory: /home/dreibh/.cache/pip/wheels/92/f0/ac/2ba2972034e98971c3654ece337ac61e546bdeb34ca960dc8c
Successfully built pyperclip
Installing collected packages: wcwidth, attrs, colorama, pyperclip, cmd2, numpy, setuptools, kiwisolver, pyparsing, six, cycler, python-dateutil, matplotlib, pytz, pandas, pbr, stevedore, mptcpanalyzer
Successfully installed attrs-19.1.0 cmd2-0.9.12 colorama-0.4.1 cycler-0.10.0 kiwisolver-1.0.1 matplotlib-3.0.3 mptcpanalyzer-0.3 numpy-1.16.3 pandas-0.24.2 pbr-5.1.3 pyparsing-2.4.0 pyperclip-1.7.0 python-dateutil-2.8.0 pytz-2019.1 setuptools-41.0.1 six-1.12.0 stevedore-1.30.1 wcwidth-0.1.7
dreibh@oesthorn:~$ mptcpanalyzer
mptcpanalyzer: command not found
dreibh@oesthorn:~$ ~/.local/bin/mptcpanalyzer 
Setting log level to ERROR
An error happened:
'MpTcpAnalyzerCmdApp' object has no attribute 'statement_parser'
Displaying backtrace:

Traceback (most recent call last):
  File "/home/dreibh/.local/lib/python3.6/site-packages/mptcpanalyzer/cli.py", line 1216, in main
    analyzer = MpTcpAnalyzerCmdApp(config, **vars(args))
  File "/home/dreibh/.local/lib/python3.6/site-packages/mptcpanalyzer/cli.py", line 136, in __init__
    self.shortcuts.update({
  File "/home/dreibh/.local/lib/python3.6/site-packages/cmd2/cmd2.py", line 570, in shortcuts
    return self.statement_parser.shortcuts
AttributeError: 'MpTcpAnalyzerCmdApp' object has no attribute 'statement_parser'

**Comment by teto** [comment]
statement_parser was introduced in cmd2 0.9.11 but you are using 0.9.12 (released 3 hours ago) let me update my version and check :D

**Comment by teto** [comment]
There are few things I want to fix before a new release (update tests, make sure the interactive help is displayed as it should which is not the case right now). Meanwhile you could try it in develop mode ? Like clone the folder and run `python3 setup.py develop `

**Comment by dreibh** [comment]
Thanks, this seems to work. I used "python3 setup.py install --user" in the Git repository.

Note, that mptcpanalyzer complained about missing "dataclasses":
ModuleNotFoundError: No module named 'dataclasses'
After "pip3 install dataclasses", it seems to be okay now. It is probably necessary to add "dataclasses" to the dependencies.

**Comment by teto** [comment]
dataclasses are part of the batteries in recent python. The current setup.py lists 3.7 as the required python. Which one are you using ?

**Comment by dreibh** [comment]
Ubuntu 18.10, which I just used to test, has Python 3.6.7 and Python 3.7.1 installed. By default, it is Python 3.6.7. May be a version check at startup could be helpful to notify the user about an incompatible version?

**Comment by teto** [comment]
I don't want to run checks at every startup since they are costly and also these kinds of checks easily break.
I just pushed a new command called `checkhealth` (similiar to neovim's `:chekhealth`) https://github.com/teto/mptcpanalyzer/commit/52a49f296bb8ecd4792e299871c4af94c9da2bed that checks:
- python version
- wireshark version
if that works well enough, I will mention it in the README/FAQ. Could you check the python check fails with python3.6 please ?

**Comment by teto** [comment]
should be fixed in new pypi release. Feel free to reopen if that's not the case.
