### ISSUE TITLE
owd is always zero

### ISSUE THREAD

**Issue by yangxuelei** [teto/pymptcpanalyzer#19]
The owd computed by "plot owd" and "print_owds" seems to be always zero. We tried with different client and server files (own files), as well as the example pcap files, e.g.:
`print_owds server_2.pcap 0 client_2.pcap 0`

Result:
```
print_owds finished
    owd
0   0.0
1   0.0
2   0.0
3   0.0
4   0.0
5   0.0
6   0.0
7   0.0
8   0.0
9   0.0
10  0.0
11  0.0
12  0.0
13  0.0
14  0.0
15  0.0
16  0.0
17  0.0
```

* mptcpanalyzer version (`$ mptcpanalyzer --version` or commit number):
Latest Git version:
commit e6e52bff229ab165dda62c20315c7d48a2b88ab1 (HEAD -> master, tag: 0.3.1, origin/master, origin/HEAD)
Author: Matthieu Coudron <mattator@gmail.com>
Date:   Fri Apr 26 16:35:03 2019 +0900

* tshark version (`$ tshark --version`, must be >= 3.X.X): 3.1.0
* python version (`$ python --version`, must be >= 3.7): 3.7.3

Output of mptcpanalyzer -dDEBUG (or -dTRACE ):
```
	HERE
```

# how to reproduce

Link to the pcap (if possible/relevant):
Own files can be provided, if necessary.

**Comment by teto** [comment]
hun that's annoying... I really need to clean up the tests.  I intended to remove print_owd (that I used just to debug) but `plot owd` should have been working since I used it.
I will fix it.Sorry for the bad experience.

**Comment by teto** [comment]
sorry for the delay, I only managed to find the (silly) mistake. The program ended up comparing the same pcaps because of this silly error:
```
        host1_df = deal_with_duplicated_hash(host1_df)
        host2_df = deal_with_duplicated_hash(host1_df) # should have been host2_df here
```
I've pushed a fix on the "next" branch. Let me know if that works for you.

**Comment by teto** [comment]
fix on master branch. Closing.
