### ISSUE TITLE
EXCEPTION of type 'MpTcpException' occurred with message: 'Could not find the client MPTCP key'

### ISSUE THREAD

**Issue by yangxuelei** [teto/pymptcpanalyzer#20]
mptcpanalyzer throws an exception when loading one of my pcap files:
```
2 mptcp connection(s)
Traceback (most recent call last):
  File "/home/long/.local/lib/python3.7/site-packages/mptcpanalyzer-0.3.1-py3.7.egg/mptcpanalyzer/cli.py", line 395, in list_subflows
    con = MpTcpConnection.build_from_dataframe(self.data, mptcpstreamid)
  File "/home/long/.local/lib/python3.7/site-packages/mptcpanalyzer-0.3.1-py3.7.egg/mptcpanalyzer/connection.py", line 375, in build_from_dataframe
    raise MpTcpException("Could not find the client MPTCP key")
mptcpanalyzer.MpTcpException: Could not find the client MPTCP key
EXCEPTION of type 'MpTcpException' occurred with message: 'Could not find the client MPTCP key'

mptcp.stream 1 has 8 subflow(s) (client/server): 
	tcp.stream 8: 2001:700:4100:5058::14:57360  -> 2001:700:4100:109::c:01935  (mptcpdest: ConnectionRoles.Server)
	tcp.stream 9: 10.80.88.20:40063  -> 10.1.9.12:01935  (mptcpdest: ConnectionRoles.Server)
	tcp.stream 10: 10.81.88.20:34997  -> 10.9.9.12:01935  (mptcpdest: ConnectionRoles.Server)
	tcp.stream 11: 2001:700:4100:5158::14:50289  -> 2001:700:4100:909::c:01935  (mptcpdest: ConnectionRoles.Server)
	tcp.stream 12: 10.81.88.20:38927  -> 10.1.9.12:01935  (mptcpdest: ConnectionRoles.Server)
	tcp.stream 13: 2001:700:4100:5158::14:48637  -> 2001:700:4100:109::c:01935  (mptcpdest: ConnectionRoles.Server)
	tcp.stream 14: 10.80.88.20:55857  -> 10.9.9.12:01935  (mptcpdest: ConnectionRoles.Server)
	tcp.stream 15: 2001:700:4100:5058::14:42647  -> 2001:700:4100:909::c:01935  (mptcpdest: ConnectionRoles.Server)

```
May be there is incomplete capture of an MPTCP connection inside the file. stream 1 is okay.

* mptcpanalyzer version (`$ mptcpanalyzer --version` or commit number):
commit e6e52bff229ab165dda62c20315c7d48a2b88ab1 (HEAD -> master, tag: 0.3.1, origin/master, origin/HEAD)
Author: Matthieu Coudron <mattator@gmail.com>
Date:   Fri Apr 26 16:35:03 2019 +0900

* tshark version (`$ tshark --version`, must be >= 3.X.X): 3.1.0
* python version (`$ python --version`, must be >= 3.7): 3.7.3

Output of mptcpanalyzer -dDEBUG (or -dTRACE ):
```
	HERE
```

# how to reproduce

Link to the pcap (if possible/relevant):
Can be provided, if useful.

**Comment by teto** [comment]
Yeah this means the capture is incomplete, like it missed the initial MPTCP handshake.
I didn't catch the exception because I wanted people to see it but it's annoying when listing the connections. I will fix it. Thanks for reporting.

**Comment by teto** [comment]
I've pushed a commit on the "next" branch to fix it https://github.com/teto/mptcpanalyzer/commit/8c84e398a203180aea9265a8be2b6810b873c55f
