### ISSUE TITLE
? is not a recognized command, alias, or macro

### ISSUE THREAD

**Issue by vandit86** [teto/pymptcpanalyzer#38]
![image](https://user-images.githubusercontent.com/16361531/118831786-f68e9f00-b8b7-11eb-8fe2-f43fbbe9f470.png)

**Comment by teto** [comment]
try `help`

**Comment by teto** [comment]
indeed `?` stopped working, certainly a change in cmd2 that I didnt see. Thanks for reporting, I'll investigate.

**Comment by vandit86** [comment]
> try `help`

"help" working well.

**Comment by teto** [comment]
fixed in https://github.com/teto/mptcpanalyzer/pull/39
